name: JavaScript - Integration Test

on: [pull_request]

jobs:
  cypress-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          command: yarn test:integration