name: TypeScript - Integration Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24.x]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test with Headless
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          headless: true
          build: npm run build
          start: npm run start
          command: npm run test:integration
